### ISSUE TITLE
Plantear Historias de Usuarios y Tareas dependientes de las US

### ISSUE THREAD

**Issue by Celeste-Miranda** [PPROF2-2022ProgWeb/g30-aula2-emprenred-g30#5]
Plantear Historias de Usuarios y Tareas dependientes de las US para incorporarlas en el repositorio remoto gitHub. (Issues y Milestones) - ej “#US01 Como usuario quiero ingresar al carrito para poder comprar”

**Comment by rebofel** [comment]
#US01 Como [usuario comprador] deseo comprar rápido y seguro desde mi celular.
