### ISSUE TITLE
Actualizar Base de Datos

### ISSUE THREAD

**Issue by Celeste-Miranda** [PPROF2-2022ProgWeb/g30-aula2-emprenred-g30#6]
- Revisar la base de datos previa en MySQL si es funcional, e incorporar nuevas tablas necesarias para el funcionamiento del módulo e-commerce. (Ver el Modelo Relacional publicado en el libro Desafío E-commerce - Proyecto de trabajo Integrador

- Crear su propio DER y Modelo relacional para documentar las tablas en la DB.

**Comment by rebofel** [comment]
#cerrada se realiza en Branch "Felipe" - EER & DB
